# Generated by Django 3.0.3 on 2020-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('Cross Platform', 'Cross Platform')], max_length=50)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
